# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
